on:
  push:
    branches:
    - kun

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: A test action from self-hosted runner
      run: |
        echo `date` >> /tmp/1
