name: A test of Github Actions

on:
  push:
    branches:
    - kun
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: a test action from self-hosted runner
      run: |
        echo `date` >> /tmp/1
